---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-1.2
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/drone-ci:1.2 -f Dockerfile-1.2 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/drone-ci:1.2
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:1.2 nephatrine/drone-ci:1.2
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:1.2
  - docker rmi pdr.nephatrine.net/nephatrine/drone-ci:1.2
- name: build-1.6
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/drone-ci:1.6 -f Dockerfile-1.6 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/drone-ci:1.6
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:1.6 nephatrine/drone-ci:1.6
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:1.6
  - docker rmi pdr.nephatrine.net/nephatrine/drone-ci:1.6
- name: build-1.7
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/drone-ci:1.7 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/drone-ci:1.7
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:1.7 nephatrine/drone-ci:1.7
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:1.7
  - docker rmi pdr.nephatrine.net/nephatrine/drone-ci:1.7
- name: build-latest
  commands:
  - docker tag nephatrine/drone-ci:1.7 pdr.nephatrine.net/nephatrine/drone-ci:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/drone-ci:latest
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:latest
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:latest
  - docker rmi pdr.nephatrine.net/nephatrine/drone-ci:latest
  depends_on:
  - build-1.7

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: webhook-id
    webhook_token:
      from_secret: webhook-token

depends_on:
- default