---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/drone-ci:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/drone-ci:latest
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:latest
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:latest
  - docker rmi pdr.nephatrine.net/nephatrine/drone-ci:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: >
      {{#success build.status}}
        "Build of **{{repo.owner}}/{{repo.name}}:{{commit.branch}}** was a {{build.status}}."
      {{else}}
        "Build of **{{repo.owner}}/{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}}). Please investigate!"
      {{/success}}
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: ff4f8ff1853ed9cfd130bcf04e487c07182762b69c501d350d2af0f8a141dd11

...
