---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-1.10
  commands:
  - docker build -t nephatrine/drone-ci:1.10 .
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:1.10
- name: build-latest
  commands:
  - docker tag nephatrine/drone-ci:1.10 pdr.nephatrine.net/nephatrine/drone-ci:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/drone-ci:latest
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:latest
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:latest
  - docker rmi pdr.nephatrine.net/nephatrine/drone-ci:latest
  depends_on:
  - build-1.10

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 0c2c3fbfe63fc90c50e2052cb755611fd9d7b69ac2a3c8e41decebf68cbd8e66

...
