---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/drone-ci:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/drone-ci:latest
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:latest
  - HOME=/mnt/config/home docker push nephatrine/drone-ci:latest
  - docker rmi pdr.nephatrine.net/nephatrine/drone-ci:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: bf9395e77cf89073e4583f3a540dbf54bd73afc24fd273708008403d40bca14b

...
